# Generated by Django 5.2.7 on 2025-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_notification_triggered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_full_name',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
